user_data_path: data/user_db.csv
win_loss_df_path: data/BaoCaoLaiLo_058C647873.csv
buy_sell_df_path: data/LichSuKhopLenh_058C647873.csv
asset_data_path: data/BaoCaoTaiSan_058C647873.csv
motif_data_path: memory/motif.csv


pvma_offset: 3 #PricevsMA
tolerance_percent: 1 #for support and resistance

pbt_params: 
- yearly # report_type
- 10 # window_size)

times:
- '10:30'
- '13:45'
- '15:00'


scape_trading_data_time: '22:59'

news_summary_time: '07:30'

help_commands_path: 'config/help_command.txt'

start_commands_path: 'config/start_command.txt'