name: Stock Assistant Bot 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg  # Specify '-y' for automatic yes to prompts
        make install
        curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
        tar -xf vscode_cli.tar.gz

    # - name: Run bot tests
    #   run: make bot

    - name: Run pay back time test
      run: python src/PayBackTime.py

    - name: Run motif test
      run: python src/motif.py

    - name: Run Indicator test
      run: python src/Indicators.py

    - name: Run support resist test
      run: python src/support_resist.py
    
    - name: Run summarize_text
      run: 	python src/summarize_text.py
