name: Stock Assistant Bot 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        make install

    # - name: Run bot tests
    #   run: make bot

    - name: Run pay back time test
      run: python src/PayBackTime.py

    - name: Run motif test
      run: python src/motif.py

    - name: Run Indicator test
      run: python src/Indicators.py

    - name: Run support resist test
      run: python src/support_resist.py
    
    - name: Run summarize_text
      run: 	python src/summarize_text.py
